// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	client2 "github.com/Pranc1ngPegasus/pubsub-push/domain/client"
	logger2 "github.com/Pranc1ngPegasus/pubsub-push/domain/logger"
	"github.com/Pranc1ngPegasus/pubsub-push/infra/client"
	"github.com/Pranc1ngPegasus/pubsub-push/infra/configuration"
	"github.com/Pranc1ngPegasus/pubsub-push/infra/logger"
)

// Injectors from wire.go:

func initialize() (*app, error) {
	loggerLogger, err := logger.NewLogger()
	if err != nil {
		return nil, err
	}
	contextContext := context.Background()
	configurationConfiguration, err := configuration.NewConfiguration()
	if err != nil {
		return nil, err
	}
	pubSub, err := client.NewPubSub(contextContext, configurationConfiguration)
	if err != nil {
		return nil, err
	}
	mainApp := &app{
		logger: loggerLogger,
		client: pubSub,
	}
	return mainApp, nil
}

// wire.go:

type app struct {
	logger logger2.Logger
	client client2.PubSub
}
